# Generated by Django 5.0.7 on 2024-07-25 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=256, verbose_name='ФИО')),
                ('mobile', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Номер телефона пользователя содержит недопустимый символ', regex='^((8|\\+7)[\\- ]?)?(\\(?\\d{3}\\)?[\\- ]?)?[\\d\\- ]{7,10}$')], verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Записи пользователей',
            },
        ),
    ]
