# Generated by Django 5.0.7 on 2024-07-29 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='mobile',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Номер телефона пользователя содержит недопустимый символ', regex='^((8|\\+7)[\\- ]?)?(\\(?\\d{3}\\)?[\\- ]?)?[\\d\\- ]{7,10}$')], verbose_name='Номер телефона'),
        ),
    ]
